#!/bin/bash
cd ..
export PYTHONPATH=".:$PYTHONPATH"

#inplane 
python3 example/spsDoor.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_32 --train-batch 2 --test-batch 1 --model_inplane 32 --epoch 250 --num_feats 32

python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_32 --train-batch 2 --test-batch 1 --model_inplane 32 --epoch 500 --num_feats 32 --resume checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_32/checkpoint.pth.tar

python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_32_aug --train-batch 2 --test-batch 1 --model_inplane 32 --epoch 750 --resume checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_32/checkpoint.pth.tar -aug --num_feats 32


python3 example/spsDoor.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_64 --train-batch 2 --test-batch 1 --model_inplane 64 --epoch 250 --num_feats 32

python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_64 --train-batch 2 --test-batch 1 --model_inplane 64 --epoch 500 --num_feats 32 --resume checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_64/checkpoint.pth.tar

python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_64_aug --train-batch 2 --test-batch 1 --model_inplane 64 --epoch 750 --resume checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_64/checkpoint.pth.tar -aug --num_feats 32


python3 example/spsDoor.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16 --train-batch 2 --test-batch 1 --model_inplane 16 --epoch 250 --num_feats 32

python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16 --train-batch 2 --test-batch 1 --model_inplane 16 --epoch 500 --num_feats 32 --resume checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16/checkpoint.pth.tar

python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16_aug --train-batch 2 --test-batch 1 --model_inplane 16 --epoch 750 --resume checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16/checkpoint.pth.tar -aug --num_feats 32


python3 example/spsDoor.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32 --train-batch 2 --test-batch 1 --model_inplane 32 --epoch 250 --num_feats 16

python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32 --train-batch 2 --test-batch 1 --model_inplane 32 --epoch 500 --num_feats 16 --resume checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32/checkpoint.pth.tar

python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32_aug --train-batch 2 --test-batch 1 --model_inplane 32 --epoch 750 --resume checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32/checkpoint.pth.tar -aug --num_feats 16




#python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16 --train-batch 2 --test-batch 1 --model_inplane 16 --epoch 500 --num_feats 32 --resume checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16/checkpoint.pth.tar

#python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16_aug --train-batch 2 --test-batch 1 --model_inplane 16 --epoch 750 --resume checkpoint/spsdoor/hourglass_1/32_feats/i256_o512_inplane_16/checkpoint.pth.tar -aug --num_feats 32

#python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32 --train-batch 2 --test-batch 1 --model_inplane 32 --epoch 500 --num_feats 16 --resume checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32/checkpoint.pth.tar

#python3 example/spsDoor2.py -a hg --checkpoint checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32_aug --train-batch 2 --test-batch 1 --model_inplane 32 --epoch 750 --resume checkpoint/spsdoor/hourglass_1/16_feats/i256_o512_inplane_32/checkpoint.pth.tar -aug --num_feats 16
